"""phase_3a_device_templates

Revision ID: 07b91ecb654b
Revises: 680b2d909867
Create Date: 2026-03-14 16:44:46.055775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07b91ecb654b'
down_revision = '680b2d909867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('make', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('ports', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_templates', schema=None) as batch_op:
        batch_op.create_index('idx_device_templates_company', ['company_id'], unique=False)
        batch_op.create_index('idx_device_templates_make_model', ['make', 'model'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_templates', schema=None) as batch_op:
        batch_op.drop_index('idx_device_templates_make_model')
        batch_op.drop_index('idx_device_templates_company')

    op.drop_table('device_templates')
    # ### end Alembic commands ###
