"""phase_3c_signal_flow

Revision ID: 2d87db24c3c4
Revises: 353afa7351dc
Create Date: 2026-03-24 18:26:57.780157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d87db24c3c4'
down_revision = '353afa7351dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_diagrams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('trade', sa.String(length=50), nullable=False),
    sa.Column('drawing_title', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('company_name_override', sa.String(length=255), nullable=True),
    sa.Column('revision', sa.String(length=50), nullable=True),
    sa.Column('drawn_by', sa.String(length=255), nullable=True),
    sa.Column('drawing_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'trade', name='uq_signal_diagram_project_trade')
    )
    with op.batch_alter_table('signal_diagrams', schema=None) as batch_op:
        batch_op.create_index('idx_signal_diagrams_project', ['project_id'], unique=False)

    op.create_table('device_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('trade', sa.String(length=50), nullable=True),
    sa.Column('source_device_id', sa.UUID(), nullable=True),
    sa.Column('source_port', sa.String(length=255), nullable=True),
    sa.Column('destination_device_id', sa.UUID(), nullable=True),
    sa.Column('destination_port', sa.String(length=255), nullable=True),
    sa.Column('connection_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_device_id'], ['project_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_device_id'], ['project_devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_connections', schema=None) as batch_op:
        batch_op.create_index('idx_device_connections_company', ['company_id'], unique=False)
        batch_op.create_index('idx_device_connections_project', ['project_id'], unique=False)

    with op.batch_alter_table('project_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trade', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_devices', schema=None) as batch_op:
        batch_op.drop_column('trade')

    with op.batch_alter_table('device_connections', schema=None) as batch_op:
        batch_op.drop_index('idx_device_connections_project')
        batch_op.drop_index('idx_device_connections_company')

    op.drop_table('device_connections')
    with op.batch_alter_table('signal_diagrams', schema=None) as batch_op:
        batch_op.drop_index('idx_signal_diagrams_project')

    op.drop_table('signal_diagrams')
    # ### end Alembic commands ###
