"""phase_3b_ip_addresses_and_categories

Revision ID: 353afa7351dc
Revises: bc24a8b18d4e
Create Date: 2026-03-15 19:09:54.724028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '353afa7351dc'
down_revision = 'bc24a8b18d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
        batch_op.drop_column('mac_address')
        batch_op.drop_column('dante_ip')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dante_ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mac_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('ip_addresses')

    # ### end Alembic commands ###
