"""add rack device fields, extra_trades, rack placement, stub_nodes

Revision ID: 42622efed0c8
Revises: 2d87db24c3c4
Create Date: 2026-03-25 23:44:26.249232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42622efed0c8'
down_revision = '2d87db24c3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rack', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('rack_units', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_back_facing', sa.Boolean(), nullable=False, server_default='false'))

    with op.batch_alter_table('project_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_trades', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('rack_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('rack_slot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rack_facing', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key(None, 'project_devices', ['rack_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('signal_diagrams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stub_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal_diagrams', schema=None) as batch_op:
        batch_op.drop_column('stub_nodes')

    with op.batch_alter_table('project_devices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rack_facing')
        batch_op.drop_column('rack_slot')
        batch_op.drop_column('rack_id')
        batch_op.drop_column('extra_trades')

    with op.batch_alter_table('device_templates', schema=None) as batch_op:
        batch_op.drop_column('is_back_facing')
        batch_op.drop_column('rack_units')
        batch_op.drop_column('is_rack')

    # ### end Alembic commands ###
