"""add attendances table

Revision ID: 680b2d909867
Revises: e7f0ce71e741
Create Date: 2026-03-10 02:24:12.251829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680b2d909867'
down_revision = 'e7f0ce71e741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_out', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', 'date', name='uq_attendance_user_date')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_company_date', ['company_id', 'date'], unique=False)
        batch_op.create_index('idx_attendance_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index('idx_attendance_user')
        batch_op.drop_index('idx_attendance_company_date')

    op.drop_table('attendances')
    # ### end Alembic commands ###
