"""add_specializations_and_trade_fields

Revision ID: b7cd6da107d9
Revises: d8378eeed0a7
Create Date: 2026-03-06 02:33:09.076973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7cd6da107d9'
down_revision = 'd8378eeed0a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specializations', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trade', sa.String(length=50), nullable=True))

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trade', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_column('trade')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('trade')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('specializations')

    # ### end Alembic commands ###
