"""phase_3b_project_devices

Revision ID: bc24a8b18d4e
Revises: e898ac48bd59
Create Date: 2026-03-15 15:42:50.878877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc24a8b18d4e'
down_revision = 'e898ac48bd59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('room', sa.String(length=255), nullable=True),
    sa.Column('rack_position', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('dante_ip', sa.String(length=50), nullable=True),
    sa.Column('stream_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('firmware_version', sa.String(length=100), nullable=True),
    sa.Column('rs232_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('node_position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['device_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_devices', schema=None) as batch_op:
        batch_op.create_index('idx_project_devices_company', ['company_id'], unique=False)
        batch_op.create_index('idx_project_devices_project', ['project_id'], unique=False)
        batch_op.create_index('idx_project_devices_template', ['template_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_devices', schema=None) as batch_op:
        batch_op.drop_index('idx_project_devices_template')
        batch_op.drop_index('idx_project_devices_project')
        batch_op.drop_index('idx_project_devices_company')

    op.drop_table('project_devices')
    # ### end Alembic commands ###
