"""replace trade varchar with trades jsonb on projects and work_orders

Revision ID: d6b66f8e795d
Revises: b7cd6da107d9
Create Date: 2026-03-07 00:29:13.221756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6b66f8e795d'
down_revision = 'b7cd6da107d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trades', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
        batch_op.drop_column('trade')

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trades', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
        batch_op.drop_column('trade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trade', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('trades')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trade', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('trades')

    # ### end Alembic commands ###
