"""add stage_requirements to workflow_stages

Revision ID: d8378eeed0a7
Revises: 4557de9134b0
Create Date: 2026-03-05 01:48:40.340413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8378eeed0a7'
down_revision = '4557de9134b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_stages', schema=None) as batch_op:
        batch_op.drop_column('stage_requirements')

    # ### end Alembic commands ###
