"""add visits and visit_assignments tables

Revision ID: e7f0ce71e741
Revises: d6b66f8e795d
Create Date: 2026-03-07 15:34:06.095168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f0ce71e741'
down_revision = 'd6b66f8e795d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index('idx_visits_company', ['company_id'], unique=False)
        batch_op.create_index('idx_visits_project', ['project_id'], unique=False)
        batch_op.create_index('idx_visits_scheduled', ['scheduled_start'], unique=False)
        batch_op.create_index('idx_visits_status', ['status'], unique=False)
        batch_op.create_index('idx_visits_work_order', ['work_order_id'], unique=False)

    op.create_table('visit_assignments',
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('visit_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_assignments')
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index('idx_visits_work_order')
        batch_op.drop_index('idx_visits_status')
        batch_op.drop_index('idx_visits_scheduled')
        batch_op.drop_index('idx_visits_project')
        batch_op.drop_index('idx_visits_company')

    op.drop_table('visits')
    # ### end Alembic commands ###
