"""phase_3a_device_template_capability_flags

Revision ID: e898ac48bd59
Revises: 07b91ecb654b
Create Date: 2026-03-14 22:59:24.665436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e898ac48bd59'
down_revision = '07b91ecb654b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_ip', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('has_web_gui', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('is_matrix', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('matrix_ports', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_templates', schema=None) as batch_op:
        batch_op.drop_column('matrix_ports')
        batch_op.drop_column('is_matrix')
        batch_op.drop_column('has_web_gui')
        batch_op.drop_column('has_ip')

    # ### end Alembic commands ###
